# Generated by Django 5.1.2 on 2024-11-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='mantenimiento/fotos')),
                ('factura', models.FileField(blank=True, null=True, upload_to='mantenimiento/facturas')),
                ('Vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
    ]
